import './globals.css';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import { getDirection } from '@/shared/lib/helpers/getDirection';

import { rHZak, montserrat } from '@/shared/lib/font';
import { Toaster } from '@/shared/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const { setDir, dirState } = getDirection(locale);

  return (
    <html
      dir={setDir}
      lang={locale}
      suppressHydrationWarning
      className={`${montserrat.variable} ${rHZak.variable}`}
      style={dirState ? rHZak.style : montserrat.style}
    >
      <body>
        <Toaster position="top-right" />
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
